export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
export const SET_CURRENT_PLAYLIST = "SET_CURRENT_PLAYLIST";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const SHUFFLE_TRACKS = "SHUFFLE_TRACKS";